### PR TITLE
Updated dependency blosc to blosc2

### PR DESCRIPTION
**Pull request by franzhuettinger**
I have only updated the dependency to blosc and changed it from blosc to blosc2. The reason for this is that blosc is no longer compatible with latest libraries and also some changes regarding NumPy were not up to date. Please feel free to add these changes to the project.

### CODE REVIEW

**Comment by AnotherSamWilson** [comment]
My man, it looks like this allows us to save objects over 2^32 bytes also. Huge improvement. Thanks.

**Comment by AnotherSamWilson** [comment]
@franzhuettinger tests failed, it looks like blosc wasn't updated in utils.

**Comment by franzhuettinger** [comment]
I forgot to update the github/workflow file. Please try again.

**Comment by AnotherSamWilson** [comment]
@franzhuettinger it looks like it still isn't updated in utils.

**Comment by franzhuettinger** [comment]
I do not see the problem at the moment but it's late today. I'll check it tomorrow.

**Comment by franzhuettinger** [comment]
In some places blosc was still used instead of blosc2. I have found these places and repaired them. I hope to have found all the places now.

**Comment by AnotherSamWilson** [comment]
@franzhuettinger hmmm it looks like the blosc2 API changed somewhat, there is no `NOSHUFFLE` option anymore. BTW, to save ourselves having to test on github, you can test locally if you install pytest and run `pytest` in your terminal.

**Comment by franzhuettinger** [comment]
I had some trouble setting up pytest on my local machine but in between I found the problem. Next commit will be tested properly.

**Comment by franzhuettinger** [comment]
```blosc2``` does not seem to be 100% compatible with ```blosc```. I had to add a compatibility layer because the codec is no longer specified as a string in ```blosc.compress()``` but as ```blosc2.Codec```. I also have to remove the ```typesize``` in ```blosc2.compress()```, because the result of dill.dumps() does not divide by ```typesize```. Another necessary change was to replace the parameter ```shuffel``` with ```filter```.

**Comment by franzhuettinger** [comment]
Still there seems to be a problem with python 3.7 and 3.8. Haven't seen this problem on my machine. Will try to find the problem tomorrow.

**Comment by franzhuettinger** [comment]
On my system, I was able to successfully complete the tests with Python 3.12, 3.9 and 3.8. I had no success with Python 3.7. Blosc2 requires at least Python 3.10 but up to version 3.8 it still seems to work without any problems.

image

If you want to maintain support for Python 3.7, then we will probably not be able to solve the problem easily. My recommendation would be to increase the minimum requirement to 3.9.

**Pull request merged**
